export enum ACTIONS {
  // App
  SET_IS_SHOWED_TO_STORE = 'SET_IS_SHOWED_TO_STORE',
  SET_IS_PINNED_TO_STORE = 'SET_IS_PINNED_TO_STORE',
  SET_POSITION_TO_STORE = 'SET_POSITION_TO_STORE',

  SET_NUMBER_TO_STORE = 'SET_NUMBER_TO_STORE',
  SET_DATE_TO_STORE = 'SET_DATE_TO_STORE',
  SET_CURRENCY_TO_STORE = 'SET_CURRENCY_TO_STORE',

  GET_EXCHANGE_RATES_REQUEST = 'GET_EXCHANGE_RATES_REQUEST',
  GET_EXCHANGE_RATES_SUCCESS = 'GET_EXCHANGE_RATES_SUCCESS',
  GET_EXCHANGE_RATES_FAILURE = 'GET_EXCHANGE_RATES_FAILURE',
  PUT_EXCHANGE_RATES_TO_STORE = 'PUT_EXCHANGE_RATES_TO_STORE',

  OPEN = 'OPEN',
  CLOSE = 'CLOSE',
}
