export enum ACTIONS {
  // App
  SET_IS_SHOWED_TO_STORE = 'SET_IS_SHOWED_TO_STORE',
  SET_IS_PINNED_TO_STORE = 'SET_IS_PINNED_TO_STORE',
  SET_POSITION_TO_STORE = 'SET_POSITION_TO_STORE',

  SET_NUMBER_TO_STORE = 'SET_NUMBER_TO_STORE',
  SET_DATE_TO_STORE = 'SET_DATE_TO_STORE',
  SET_CURRENCY_TO_STORE = 'SET_CURRENCY_TO_STORE',

  OPEN = 'OPEN',
  CLOSE = 'CLOSE',

  //Options
  SET_OPTIONS_TO_STORE = 'SET_OPTIONS_TO_STORE',

  SET_IS_PAGE_TOOLTIP_TO_STORE = 'SET_IS_PAGE_TOOLTIP_TO_STORE',
  SET_API_TO_STORE = 'SET_API_TO_STORE',
  SET_NAMING_TO_STORE = 'SET_NAMING_TO_STORE',
  SET_FAVORITES_TO_STORE = 'SET_FAVORITES_TO_STORE',
}
