export enum ACTIONS {
  // Options
  SET_OPTIONS_TO_STORE = 'SET_OPTIONS_TO_STORE',

  SET_IS_PAGE_TOOLTIP_TO_STORE = 'SET_IS_PAGE_TOOLTIP_TO_STORE',
  SET_API_TO_STORE = 'SET_API_TO_STORE',
  SET_NAMING_TO_STORE = 'SET_NAMING_TO_STORE',
  SET_FAVORITES_TO_STORE = 'SET_FAVORITES_TO_STORE',

  SET_LATEST_CURRENCY_TO_STORE = 'SET_LATEST_CURRENCY_TO_STORE',
}
