export enum ACTIONS {
  // App
  SET_TAB_TO_STORE = 'SET_TAB_TO_STORE',

  SET_NUMBER_TO_STORE = 'SET_NUMBER_TO_STORE',
  SET_DATE_TO_STORE = 'SET_DATE_TO_STORE',

  GET_EXCHANGE_RATES_REQUEST = 'GET_EXCHANGE_RATES_REQUEST',
  GET_EXCHANGE_RATES_SUCCESS = 'GET_EXCHANGE_RATES_SUCCESS',
  GET_EXCHANGE_RATES_FAILURE = 'GET_EXCHANGE_RATES_FAILURE',
  PUT_EXCHANGE_RATES_TO_STORE = 'PUT_EXCHANGE_RATES_TO_STORE',

  GET_EXCHANGE_RATES_CRYPTO_REQUEST = 'GET_EXCHANGE_RATES_CRYPTO_REQUEST',
  GET_EXCHANGE_RATES_CRYPTO_SUCCESS = 'GET_EXCHANGE_RATES_CRYPTO_SUCCESS',
  GET_EXCHANGE_RATES_CRYPTO_FAILURE = 'GET_EXCHANGE_RATES_CRYPTO_FAILURE',
  PUT_EXCHANGE_RATES_CRYPTO_TO_STORE = 'PUT_EXCHANGE_RATES_CRYPTO_TO_STORE',
}
